Repository ReliefApplications/oort-backend, pull requests merged in 2024-01, with the labels that each got.

#13 fix/HIT-194_Sometimes the schema randomly breaks
  src/utils/schema/buildSchema.ts
Labels: bug

#18 HIT-211: Added 'in', 'notin', 'issubset', 'isnotsubset' operators for context filters
  src/security/extendAbilityForContent.ts
  src/utils/schema/resolvers/Query/getFilter.ts
Labels: enhancement

#19 HIT-71-still-an-error-message-when-saving-register-a-complaint-although-changes-are-still-saved
  src/utils/form/preserveChildProperties.ts
Labels: bug

#20 fix/HIT-212_Structure-apps-are-not-copying-the-dashboard-filters
  src/utils/alimentaide/onStructureAdded.ts
Labels: bug, enhancement

#21 Feat/hit 213 configuration on guyane new calculated field trim
  src/const/calculatedFields.ts
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
  src/utils/aggregation/expressionFromString.ts
  src/utils/alimentaide/onStructureAdded.ts
Labels: enhancement

#24 fix/HIT-219_Dashboard-filter-working-only-if-field-is-selected-in-the-aggregation
  src/schema/query/recordsAggregation.query.ts
Labels: bug

#27 fix/HIT-227 Dashboard filter not working when using an array to filter a field of primitive type
  src/utils/schema/resolvers/Query/getFilter.ts
Labels: bug

#28 HIT-229 dashboard filter doesnt work on widgets that dont have the field to be filtered from in its aggregation
  src/schema/query/recordsAggregation.query.ts
Labels: bug
